language: go
go: 1.1.1
install:
  - sudo git clone https://git.fedorahosted.org/git/lvm2.git /usr/local/lvm2
  - pushd /usr/local/lvm2
  - sudo git checkout v2_02_103
  - sudo ./configure --enable-static_link
  - sudo make device-mapper
  - sudo make install_device-mapper
  - popd
  - go get -d ./...
  - go get github.com/globocom/tsuru/safe
script:
  - go test -race ./...
