language: go
go:
  - 1.2
  - 1.3
  - tip
install:
  - go get -d -t ./...
  - go get code.google.com/p/go.tools/cmd/vet
script:
  - go test -race ./...
  - go vet ./...
services:
  - redis-server
  - mongodb
