language: go
sudo: false
go:
  - 1.5.3
  - 1.6
  - tip
install:
  - go get -d -t ./...
script:
  - go test -race ./...
  - go vet ./...
services:
  - redis-server
  - mongodb
matrix:
  allow_failures:
    - go: tip
